# Generated by Django 3.2.6 on 2021-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('utlLesson', models.URLField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
    ]
