# Generated by Django 3.2.6 on 2021-08-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HashedVideos',
        ),
    ]
