# Generated by Django 3.2.6 on 2021-08-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210805_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
    ]
