# Generated by Django 3.2.6 on 2021-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_hashedvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
